# Generated by Django 4.2.6 on 2023-10-29 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertificateTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="certificates")),
                ("exercises", models.IntegerField()),
                ("project", models.IntegerField()),
                ("src", models.URLField(blank=True, null=True)),
                ("course", models.URLField(blank=True, null=True)),
                (
                    "importance",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "topics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.certificatetopic",
                    ),
                ),
            ],
            options={
                "ordering": ["-importance"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="projects")),
                ("demo", models.TextField(blank=True, null=True)),
                ("online", models.URLField(blank=True, null=True)),
                ("code", models.URLField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("release", models.DateField()),
                (
                    "importance",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="available_projects",
                        to="blog.certificate",
                    ),
                ),
            ],
            options={
                "ordering": ["-importance", "-release"],
                "indexes": [
                    models.Index(
                        fields=["-importance", "-release"],
                        name="blog_projec_importa_390ecd_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["importance"], name="blog_certif_importa_e90550_idx"
            ),
        ),
    ]
