# Generated by Django 4.2.6 on 2023-10-29 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_project_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="mobile_image",
            field=models.ImageField(blank=True, null=True, upload_to="projects"),
        ),
        migrations.AlterField(
            model_name="project",
            name="certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="available_projects",
                to="blog.certificate",
            ),
        ),
    ]
