# Generated by Django 4.2.6 on 2023-10-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_project_mobile_image_alter_project_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="topics",
        ),
        migrations.AddField(
            model_name="certificate",
            name="topics",
            field=models.ManyToManyField(to="blog.certificatetopic"),
        ),
    ]
