# Generated by Django 4.2.6 on 2023-11-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_project_youtube_id_alter_certificate_image_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CertificateTopic",
            new_name="Tecnology",
        ),
        migrations.RemoveField(
            model_name="project",
            name="youtube_id",
        ),
        migrations.AlterField(
            model_name="certificate",
            name="image",
            field=models.ImageField(upload_to="certificates"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="projects"),
        ),
    ]
