# Generated by Django 4.2.6 on 2023-11-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_certificate_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tecnologies",
            field=models.ManyToManyField(related_name="projects", to="blog.tecnology"),
        ),
    ]
