# Generated by Django 4.2.6 on 2023-11-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_project_tecnologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="youtube_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
