# Generated by Django 4.2.6 on 2023-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_project_youtube_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="image",
            field=models.ImageField(upload_to="media/certificates"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="media/projects"),
        ),
    ]
