# Generated by Django 4.2.6 on 2023-11-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_alter_certificate_image_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="image",
            field=models.ImageField(upload_to="certificates"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="projects"),
        ),
    ]
